# Generated by Django 4.0.4 on 2022-05-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesList',
            fields=[
                ('category_name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('subscription_cost', models.IntegerField(null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('categorylist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.categorieslist')),
            ],
        ),
    ]
