# Generated by Django 4.0.4 on 2022-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_orderspayment_paymentproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderspayment',
            name='payment_id',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
